USE Livraria;

CREATE TABLE Autores(
	idAutor UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	nomeAutor VARCHAR(100) NOT NULL,
	nacionalidadeAutor VARCHAR(100) NOT NULL
);

CREATE TABLE Livros(
	idLivro UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	tituloLivro VARCHAR(100) NOT NULL,
	anoLivro INT NOT NULL,
	qtdeLivro INT NOT NULL,
	idAutor UNIQUEIDENTIFIER,
	FOREIGN KEY (idAutor) REFERENCES Autores(idAutor)
);

CREATE TABLE Clientes(
	idCliente UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	nomeCliente VARCHAR(100) NOT NULL,
	emailCliente VARCHAR(100) NOT NULL,
	telCliente VARCHAR(25) NOT NULL
);

CREATE TABLE Emprestimos(
	idEmprestimo UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	dataEmprestimo DATE NOT NULL,
	devolucaoEmprestimo DATE NOT NULL,
	idLivro UNIQUEIDENTIFIER,
	idCliente UNIQUEIDENTIFIER,
	FOREIGN KEY (idLivro) REFERENCES Livros(idLivro),
	FOREIGN KEY (idCliente) REFERENCES Clientes(idcliente)
);


